name: Build, zip and upload source
version: 2.1

on:
  push:
    branches:
      - "cicd"

jobs:
  validate-terraform:
    name: Validate
    runs-on: ubuntu-latest
    docker:
      - image: hashicorp/terraform:0.12.28
    working_directory: /tmp/workspace
    steps:
      - checkout:
          path: ~/repo
      - name: Validate terraform code
        command: |
          printf "Validating terraform code\n"
          cd ~/repo/terraform
          (cd prod && terraform init -backend=false && terraform validate)
