name: Build, zip and upload source
version: 2.1

on:
  push:
    branches:
      - "cicd"

jobs:
  validate-terraform:
    name: Run terraform init
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: |
          ls
      - name: Run a Terraform init
        uses: docker://hashicorp/terraform:0.12.28
        with:
          entrypoint: terraform/prod
          args: init
