name: "Terraform"

on:
  push:
    branches:
      - "cicd"

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init
        run: |
          cd terraform/prod
          terraform init

      - name: Terraform format check
        run: |
          terraform fmt -check
