name: 'Hello World'

on:
  push:
    branches:
      - master

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print 'Hello World' to console
        run: >-
          echo "Hello from Github action!"

